import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import 'flight_derived_stats.dart';
import 'flight_recorder.dart';

/// Generates a one-page PDF summary report for a completed [FlightTrack] and
/// shares it via the platform share sheet.
///
/// Self-contained port of the reference project's flight PDF report, adapted to
/// this project's model. The report shows the headline summary statistics plus
/// the derived performance metrics from [FlightDerivedStats].
class FlightReportService {
  FlightReportService._();
  static final FlightReportService instance = FlightReportService._();

  /// Builds the PDF bytes for [track].
  Future<List<int>> buildPdf(FlightTrack track) async {
    final stats = FlightDerivedStats.compute(track);
    final doc = pw.Document();

    final title = 'Flight ${flightSlug(track)}';

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'ParaBeacon Flight Report',
                style: pw.TextStyle(
                  fontSize: 22,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 2),
              pw.Text(title, style: const pw.TextStyle(fontSize: 12)),
              pw.Divider(),
              pw.SizedBox(height: 8),
              _section('Summary'),
              _table([
                ['Date', _fmtDate(track.startTime)],
                ['Start', _fmtTime(track.startTime)],
                [
                  'End',
                  track.endTime != null ? _fmtTime(track.endTime!) : '—',
                ],
                ['Duration', _fmtDuration(track.duration)],
                ['Track points', '${track.pointCount}'],
              ]),
              pw.SizedBox(height: 12),
              _section('Distance & altitude'),
              _table([
                ['Track distance', _km(stats.trackDistanceM)],
                ['Straight distance', _km(stats.straightDistanceM)],
                ['Max from start', _km(stats.maxDistanceFromStartM)],
                ['Max altitude', '${track.maxAltitude.toStringAsFixed(0)} m'],
                ['Min altitude', '${track.minAltitude.toStringAsFixed(0)} m'],
                [
                  'Altitude gained',
                  '${stats.altitudeGainedM.toStringAsFixed(0)} m'
                ],
                [
                  'Altitude lost',
                  '${stats.altitudeLostM.toStringAsFixed(0)} m'
                ],
              ]),
              pw.SizedBox(height: 12),
              _section('Performance'),
              _table([
                [
                  'Avg ground speed',
                  '${stats.avgGroundSpeedKph.toStringAsFixed(1)} km/h'
                ],
                [
                  'Avg cruise speed',
                  '${stats.avgCruiseSpeedKph.toStringAsFixed(1)} km/h'
                ],
                ['Max speed', '${stats.maxSpeedKph.toStringAsFixed(1)} km/h'],
                ['Max climb', '${track.maxClimb.toStringAsFixed(1)} m/s'],
                ['Max sink', '${track.maxSink.toStringAsFixed(1)} m/s'],
                [
                  'Avg climb',
                  '${stats.avgClimbMs.toStringAsFixed(1)} m/s'
                ],
                ['Avg sink', '${stats.avgSinkMs.toStringAsFixed(1)} m/s'],
                [
                  'Avg glide ratio',
                  stats.avgGlideRatio > 0
                      ? stats.avgGlideRatio.toStringAsFixed(1)
                      : '—'
                ],
                [
                  'Track efficiency',
                  '${(stats.trackEfficiency * 100).toStringAsFixed(0)} %'
                ],
                ['Thermals', '${stats.thermalCount}'],
                ['Climb time', _fmtDuration(stats.climbTime)],
                ['Glide time', _fmtDuration(stats.glideTime)],
                ['Sink time', _fmtDuration(stats.sinkTime)],
                ['Moving time', _fmtDuration(stats.movingTime)],
              ]),
              pw.Spacer(),
              pw.Text(
                'Generated by ParaBeacon',
                style: const pw.TextStyle(
                  fontSize: 9,
                  color: PdfColors.grey600,
                ),
              ),
            ],
          );
        },
      ),
    );

    return doc.save();
  }

  /// Builds the report and shares it as a `.pdf` file. Returns the temp path.
  Future<String> sharePdf(FlightTrack track) async {
    final bytes = await buildPdf(track);
    final dir = await getTemporaryDirectory();
    final fileName = '${flightSlug(track)}.pdf';
    final path = p.join(dir.path, fileName);
    await File(path).writeAsBytes(bytes, flush: true);
    await Share.shareXFiles(
      [XFile(path, mimeType: 'application/pdf', name: fileName)],
      subject: 'ParaBeacon flight ${flightSlug(track)}',
    );
    return path;
  }

  // ── Small PDF helpers ─────────────────────────────────────────────────────

  static pw.Widget _section(String title) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 4),
        child: pw.Text(
          title,
          style: pw.TextStyle(
            fontSize: 14,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.blueGrey800,
          ),
        ),
      );

  static pw.Widget _table(List<List<String>> rows) {
    return pw.Table(
      columnWidths: const {
        0: pw.FlexColumnWidth(2),
        1: pw.FlexColumnWidth(3),
      },
      children: [
        for (final r in rows)
          pw.TableRow(
            children: [
              pw.Padding(
                padding: const pw.EdgeInsets.symmetric(vertical: 2),
                child: pw.Text(
                  r[0],
                  style: const pw.TextStyle(
                    fontSize: 11,
                    color: PdfColors.grey700,
                  ),
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.symmetric(vertical: 2),
                child: pw.Text(
                  r[1],
                  style: pw.TextStyle(
                    fontSize: 11,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
      ],
    );
  }

  static String _km(double m) => m >= 1000
      ? '${(m / 1000).toStringAsFixed(2)} km'
      : '${m.toStringAsFixed(0)} m';

  static String _fmtDate(DateTime t) =>
      '${t.year}-${_two(t.month)}-${_two(t.day)}';

  static String _fmtTime(DateTime t) => '${_two(t.hour)}:${_two(t.minute)}';

  static String _fmtDuration(Duration d) {
    final h = d.inHours;
    final m = d.inMinutes % 60;
    final s = d.inSeconds % 60;
    if (h > 0) return '${h}h ${_two(m)}m';
    return '${m}m ${_two(s)}s';
  }

  static String _two(int n) => n.toString().padLeft(2, '0');
}
